USE [master]
GO

/****** Object:  Database [suetest]    Script Date: 11/28/2016 2:11:33 PM ******/
CREATE DATABASE [suetest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'suetest', FILENAME = N'/var/opt/mssql/data/data1/sql_db/suetest.MDF' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'suetest_log', FILENAME = N'/var/opt/mssql/data/data2/sql_db/suetest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

--ALTER DATABASE [suetest] SET COMPATIBILITY_LEVEL = 130
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [suetest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [suetest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [suetest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [suetest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [suetest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [suetest] SET ARITHABORT OFF 
GO

ALTER DATABASE [suetest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [suetest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [suetest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [suetest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [suetest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [suetest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [suetest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [suetest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [suetest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [suetest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [suetest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [suetest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [suetest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [suetest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [suetest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [suetest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [suetest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [suetest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [suetest] SET  MULTI_USER 
GO

ALTER DATABASE [suetest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [suetest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [suetest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [suetest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [suetest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [suetest] SET QUERY_STORE = OFF
GO

USE [suetest]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [suetest] SET  READ_WRITE 
GO


